apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculadora-salarial.fullname" . }}
  labels:
    app: {{ include "calculadora-salarial.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "calculadora-salarial.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "calculadora-salarial.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
